version: 0.4.0.{build}

environment:
  exe_version: 0.4.0
  lib_version: 0.4.0
  github_token:
    secure: TXxOh3NI3UV0tNKI9snSVmZPFKvpqfhJgDpr7M9GDLS9DSX32P9NGdjIWVwYX+Mc
  appveyor_token:
    secure: IV7vyJWe55+8yxcfF7+dUEHN2b4yGL0RDsgH9T7kZQE=

shallow_clone: true
clone_depth: 5  

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

assembly_info:
  patch: true
  file: TpacTool\Properties\AssemblyInfo.cs
  assembly_version: $(exe_version)
  assembly_file_version: $(exe_version)
  assembly_informational_version: $(exe_version)

dotnet_csproj:
  patch: true
  file: '**\TpacTool.Lib.csproj;**\TpacTool.IO.csproj;**\TpacTool.IO.Assimp.csproj'
  version: $(lib_version)
  package_version: $(lib_version)
  assembly_version: $(lib_version)
  file_version: $(lib_version)
  informational_version: $(lib_version)

image: Visual Studio 2022
configuration: Release
platform: Any CPU

before_build:
  - nuget restore

build:
  parallel: true

after_build:
  - ps: Rename-Item TpacTool\bin\Release TpacTool
  - ps: $env:ARTIFACT_NAME = "TpacTool_" + $env:exe_version + ".zip"
  - ps: cd TpacTool\bin
  - ps: 7z a $env:ARTIFACT_NAME -r .\
  - ps: Copy-Item $env:ARTIFACT_NAME ..\..\
  
artifacts:
  - path: TpacTool_${exe_version}.zip
    name: TpacToolExe
    type: zip

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ''
    auth_token: $(github_token)
    artifact: TpacToolExe
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
