//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpacTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TpacTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Author: szszss 的本地化字符串。
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string About_Close {
            get {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     TpacTool is a software for viewing and unpacking the tpac files of Mount&amp;Blade II: Bannerlord. 的本地化字符串。
        /// </summary>
        public static string About_Intro {
            get {
                return ResourceManager.GetString("About_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website: 的本地化字符串。
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bones: 的本地化字符串。
        /// </summary>
        public static string Animation_Bones {
            get {
                return ResourceManager.GetString("Animation_Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Animation_Export {
            get {
                return ResourceManager.GetString("Animation_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_1 {
            get {
                return ResourceManager.GetString("Animation_Export_FR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export at one frame per second to ensure the modeling software won&apos;t miss any frames. 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_1_Tooltip {
            get {
                return ResourceManager.GetString("Animation_Export_FR_1_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_24 {
            get {
                return ResourceManager.GetString("Animation_Export_FR_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export at 24 frames per second, the default frame rate of Maya and Blender.
        ///The exporting frame rate should match the frame rate of the modeling software you are using. Exporting at a higher frame rate than the software will cause some animation frames to be lost. 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_24_Tooltip {
            get {
                return ResourceManager.GetString("Animation_Export_FR_24_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 25 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_25 {
            get {
                return ResourceManager.GetString("Animation_Export_FR_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export at 25 frames per second, the frame rate of PAL standard.
        ///The exporting frame rate should match the frame rate of the modeling software you are using. Exporting at a higher frame rate than the software will cause some animation frames to be lost. 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_25_Tooltip {
            get {
                return ResourceManager.GetString("Animation_Export_FR_25_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_30 {
            get {
                return ResourceManager.GetString("Animation_Export_FR_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export at 30 frames per second, the default frame rate of 3ds Max.
        ///The exporting frame rate should match the frame rate of the modeling software you are using. Exporting at a higher frame rate than the software will cause some animation frames to be lost. 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_30_Tooltip {
            get {
                return ResourceManager.GetString("Animation_Export_FR_30_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 60 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_60 {
            get {
                return ResourceManager.GetString("Animation_Export_FR_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export at 60 frames per second. Most of animations in the game are at this frame rate.
        ///The exporting frame rate should match the frame rate of the modeling software you are using. Exporting at a higher frame rate than the software will cause some animation frames to be lost. 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FR_60_Tooltip {
            get {
                return ResourceManager.GetString("Animation_Export_FR_60_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Rate 的本地化字符串。
        /// </summary>
        public static string Animation_Export_FrameRate {
            get {
                return ResourceManager.GetString("Animation_Export_FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Animation_Info {
            get {
                return ResourceManager.GetString("Animation_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model: 的本地化字符串。
        /// </summary>
        public static string Animation_Model {
            get {
                return ResourceManager.GetString("Animation_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female Head 的本地化字符串。
        /// </summary>
        public static string Animation_Model_FemaleHead {
            get {
                return ResourceManager.GetString("Animation_Model_FemaleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male Head 的本地化字符串。
        /// </summary>
        public static string Animation_Model_MaleHead {
            get {
                return ResourceManager.GetString("Animation_Model_MaleHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skeleton: 的本地化字符串。
        /// </summary>
        public static string Animation_Skeleton {
            get {
                return ResourceManager.GetString("Animation_Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Animation_Skeleton_Default {
            get {
                return ResourceManager.GetString("Animation_Skeleton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geometry 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Geometry {
            get {
                return ResourceManager.GetString("Asset_Type_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Material {
            get {
                return ResourceManager.GetString("Asset_Type_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Model {
            get {
                return ResourceManager.GetString("Asset_Type_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Morph 的本地化字符串。
        /// </summary>
        public static string Asset_Type_MorphAnimation {
            get {
                return ResourceManager.GetString("Asset_Type_MorphAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Particle {
            get {
                return ResourceManager.GetString("Asset_Type_Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physics Shape 的本地化字符串。
        /// </summary>
        public static string Asset_Type_PhysicsShape {
            get {
                return ResourceManager.GetString("Asset_Type_PhysicsShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PVF 的本地化字符串。
        /// </summary>
        public static string Asset_Type_ProceduralVectorField {
            get {
                return ResourceManager.GetString("Asset_Type_ProceduralVectorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Shader {
            get {
                return ResourceManager.GetString("Asset_Type_Shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animation 的本地化字符串。
        /// </summary>
        public static string Asset_Type_SkeletalAnimation {
            get {
                return ResourceManager.GetString("Asset_Type_SkeletalAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skeleton 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Skeleton {
            get {
                return ResourceManager.GetString("Asset_Type_Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture 的本地化字符串。
        /// </summary>
        public static string Asset_Type_Texture {
            get {
                return ResourceManager.GetString("Asset_Type_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string AssetTree_Filter_Tooltip {
            get {
                return ResourceManager.GetString("AssetTree_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear filter pattern 的本地化字符串。
        /// </summary>
        public static string AssetTree_FilterRemove_Tooltip {
            get {
                return ResourceManager.GetString("AssetTree_FilterRemove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grouped by package 的本地化字符串。
        /// </summary>
        public static string AssetTree_Grouped_Tooltip {
            get {
                return ResourceManager.GetString("AssetTree_Grouped_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Loading_Cancel {
            get {
                return ResourceManager.GetString("Loading_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching tpac ... 的本地化字符串。
        /// </summary>
        public static string Loading_Searching {
            get {
                return ResourceManager.GetString("Loading_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Loading_Title {
            get {
                return ResourceManager.GetString("Loading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the AssetPackages folder 的本地化字符串。
        /// </summary>
        public static string Main_Dialog_SelectAssetPackages {
            get {
                return ResourceManager.GetString("Main_Dialog_SelectAssetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string Main_Menu_File {
            get {
                return ResourceManager.GetString("Main_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Main_Menu_File_Exit {
            get {
                return ResourceManager.GetString("Main_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open AssetPackages Folder ... 的本地化字符串。
        /// </summary>
        public static string Main_Menu_File_OpenAssetFolder {
            get {
                return ResourceManager.GetString("Main_Menu_File_OpenAssetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setti_ngs 的本地化字符串。
        /// </summary>
        public static string Main_Menu_Settings {
            get {
                return ResourceManager.GetString("Main_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Main_Menu_Settings_About {
            get {
                return ResourceManager.GetString("Main_Menu_Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        public static string Main_Menu_Settings_Languages {
            get {
                return ResourceManager.GetString("Main_Menu_Settings_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Main_Menu_Settings_Languages_Default {
            get {
                return ResourceManager.GetString("Main_Menu_Settings_Languages_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all non-tileset textures to ... 的本地化字符串。
        /// </summary>
        public static string Material_Dialog_SelectExportDir {
            get {
                return ResourceManager.GetString("Material_Dialog_SelectExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Material_Export {
            get {
                return ResourceManager.GetString("Material_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred format 的本地化字符串。
        /// </summary>
        public static string Material_Export_PreferredFormat {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any 的本地化字符串。
        /// </summary>
        public static string Material_Export_PreferredFormat_Any {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DDS first 的本地化字符串。
        /// </summary>
        public static string Material_Export_PreferredFormat_Dds {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Dds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG first 的本地化字符串。
        /// </summary>
        public static string Material_Export_PreferredFormat_Png {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Which format is preferred for export. 的本地化字符串。
        /// </summary>
        public static string Material_Export_PreferredFormat_Tooltip {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Material_Preview {
            get {
                return ResourceManager.GetString("Material_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string Material_Properties {
            get {
                return ResourceManager.GetString("Material_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alpha Test: 的本地化字符串。
        /// </summary>
        public static string Material_Properties_AlphaTest {
            get {
                return ResourceManager.GetString("Material_Properties_AlphaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blend Mode: 的本地化字符串。
        /// </summary>
        public static string Material_Properties_BlendMode {
            get {
                return ResourceManager.GetString("Material_Properties_BlendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flags 的本地化字符串。
        /// </summary>
        public static string Material_Properties_Flags {
            get {
                return ResourceManager.GetString("Material_Properties_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Material_Properties_Info {
            get {
                return ResourceManager.GetString("Material_Properties_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader: 的本地化字符串。
        /// </summary>
        public static string Material_Properties_Shader {
            get {
                return ResourceManager.GetString("Material_Properties_Shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Hints 的本地化字符串。
        /// </summary>
        public static string Material_Properties_ShaderHints {
            get {
                return ResourceManager.GetString("Material_Properties_ShaderHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show empty slots 的本地化字符串。
        /// </summary>
        public static string Material_Properties_ShowEmptySlots {
            get {
                return ResourceManager.GetString("Material_Properties_ShowEmptySlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the texture slots which aren&apos;t assigned texture 的本地化字符串。
        /// </summary>
        public static string Material_Properties_ShowEmptySlots_Tooltip {
            get {
                return ResourceManager.GetString("Material_Properties_ShowEmptySlots_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textures: 的本地化字符串。
        /// </summary>
        public static string Material_Properties_Textures {
            get {
                return ResourceManager.GetString("Material_Properties_Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertex Layout Hints 的本地化字符串。
        /// </summary>
        public static string Material_Properties_VertexLayoutHints {
            get {
                return ResourceManager.GetString("Material_Properties_VertexLayoutHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export model to ... 的本地化字符串。
        /// </summary>
        public static string Model_Dialog_SelectExportFile {
            get {
                return ResourceManager.GetString("Model_Dialog_SelectExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Model_Export {
            get {
                return ResourceManager.GetString("Model_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOD 的本地化字符串。
        /// </summary>
        public static string Model_Export_Lod {
            get {
                return ResourceManager.GetString("Model_Export_Lod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All LODs 的本地化字符串。
        /// </summary>
        public static string Model_Export_Lod_AllLods {
            get {
                return ResourceManager.GetString("Model_Export_Lod_AllLods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all LODs. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Lod_AllLods_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Lod_AllLods_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only LOD 0 的本地化字符串。
        /// </summary>
        public static string Model_Export_Lod_Only0 {
            get {
                return ResourceManager.GetString("Model_Export_Lod_Only0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only export LOD 0, the highest definition model. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Lod_Only0_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Lod_Only0_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material &amp; Texture 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material {
            get {
                return ResourceManager.GetString("Model_Export_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only export diffuse (color) texture 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_DiffuseOnly {
            get {
                return ResourceManager.GetString("Model_Export_Material_DiffuseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only the diffuse (ie color) texture will be exported. Note that this option will also affect the model file itself. The materials in the model file will no longer include textures other than diffuse. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_DiffuseOnly_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_DiffuseOnly_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to same folder 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_ExportSame {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the texture files to the same folder with the exported model. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_ExportSame_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSame_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to sub folder 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_ExportSub {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the texture files to a folder named after the exported model. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_ExportSub_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSub_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t export 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_NoExport {
            get {
                return ResourceManager.GetString("Model_Export_Material_NoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not export the texture files which the model uses. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Material_NoExport_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_NoExport_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misc 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc {
            get {
                return ResourceManager.GetString("Model_Export_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FBX: Export as text 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_FbxAsText {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FbxAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export models in readable text format. This option is not very useful because many software cannot import text-formatted FBX. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_FbxAsText_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FbxAsText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FBX: Export in meters 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_FbxInMeters {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FbxInMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By default, FBX is in centimeters, but some software (such as Blender) imports models in meters. Check this option to export models in meters. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_FbxInMeters_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FbxInMeters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DAE: Fix the bone connections for Blender 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_FixBoneConnect {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FixBoneConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add metadata for Blender to identify bone connections. Even if you do not check this option, the connection can be repaired by adjusting the configuration of the DAE importer of Blender. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_FixBoneConnect_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FixBoneConnect_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Larger scale 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_LargerScale {
            get {
                return ResourceManager.GetString("Model_Export_Misc_LargerScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enlarging the size of the exported model. For the formats which support node (eg DAE) it will enlarge the scale of root node.  For others (eg OBJ) it will directly enlarge the mesh. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_LargerScale_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_LargerScale_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negative-Y-forward axis 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_NYForward {
            get {
                return ResourceManager.GetString("Model_Export_Misc_NYForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By default, the exported model faces to +Y. Check this option to make it facing to -Y. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_NYForward_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_NYForward_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OBJ: Y-upward axis 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_YUpAxis {
            get {
                return ResourceManager.GetString("Model_Export_Misc_YUpAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By default, the exported model uses the Z axis as the upward axis. However, some OBJ importers use the Y axis as the upward axis. Check this option to export the OBJ model with Y-upward axis style. 的本地化字符串。
        /// </summary>
        public static string Model_Export_Misc_YUpAxis_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_YUpAxis_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skeleton 的本地化字符串。
        /// </summary>
        public static string Model_Export_Skeleton {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horse 的本地化字符串。
        /// </summary>
        public static string Model_Export_Skeleton_Horse {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton_Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Human 的本地化字符串。
        /// </summary>
        public static string Model_Export_Skeleton_Human {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Model_Export_Skeleton_Other {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Model_Export_Type {
            get {
                return ResourceManager.GetString("Model_Export_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rigged 的本地化字符串。
        /// </summary>
        public static string Model_Export_Type_Rigged {
            get {
                return ResourceManager.GetString("Model_Export_Type_Rigged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        public static string Model_Export_Type_Static {
            get {
                return ResourceManager.GetString("Model_Export_Type_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Per-mesh Properties 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clothing Material 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air Drag Multiplier: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_ADM {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_ADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anchor Stiffness: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_AS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bending Stiffness: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_BS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damping: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_Damping {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Damping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gravity: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_Gravity {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear Inertia: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_LI {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear Velocity Multiplier: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_LVM {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_LVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Linear Velocity: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_MLV {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_MLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_Name {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shearing Stiffness: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_ShS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_ShS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stretching Stiffness: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_StS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_StS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wind: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_CM_Wind {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Face {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flags 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Flags {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has Morph 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_HasMorph {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_HasMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Info {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Rigged 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_IsRigged {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_IsRigged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lod: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Lod {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Lod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Material {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Hints 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_MaterialHints {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_MaterialHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Name {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SecMat: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_SecMat {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_SecMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertex: 的本地化字符串。
        /// </summary>
        public static string Model_PerMeshProperties_Vertex {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Model_Preview {
            get {
                return ResourceManager.GetString("Model_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOD: 的本地化字符串。
        /// </summary>
        public static string Model_Preview_Lod {
            get {
                return ResourceManager.GetString("Model_Preview_Lod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string Model_Preview_Show {
            get {
                return ResourceManager.GetString("Model_Preview_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot export animation with Assimp. 的本地化字符串。
        /// </summary>
        public static string Msgbox_AnimationAssimpRequired {
            get {
                return ResourceManager.GetString("Msgbox_AnimationAssimpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot initialize Assimp. FBX exporting is unavailable. 的本地化字符串。
        /// </summary>
        public static string Msgbox_AssimpNotFound {
            get {
                return ResourceManager.GetString("Msgbox_AssimpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find/load the default skeleton of this animation.  的本地化字符串。
        /// </summary>
        public static string Msgbox_DefaultSkeletonNotFound {
            get {
                return ResourceManager.GetString("Msgbox_DefaultSkeletonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory doesn&apos;t exist 的本地化字符串。
        /// </summary>
        public static string Msgbox_DirNotExisting {
            get {
                return ResourceManager.GetString("Msgbox_DirNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Msgbox_Error {
            get {
                return ResourceManager.GetString("Msgbox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find female head model. 的本地化字符串。
        /// </summary>
        public static string Msgbox_FemaleHeadModelNotFound {
            get {
                return ResourceManager.GetString("Msgbox_FemaleHeadModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find horse skeleton. 的本地化字符串。
        /// </summary>
        public static string Msgbox_HorseSkeletonNotFound {
            get {
                return ResourceManager.GetString("Msgbox_HorseSkeletonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find human skeleton. 的本地化字符串。
        /// </summary>
        public static string Msgbox_HumanSkeletonNotFound {
            get {
                return ResourceManager.GetString("Msgbox_HumanSkeletonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Msgbox_Info {
            get {
                return ResourceManager.GetString("Msgbox_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find male head model. 的本地化字符串。
        /// </summary>
        public static string Msgbox_MaleHeadModelNotFound {
            get {
                return ResourceManager.GetString("Msgbox_MaleHeadModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to select a model from the combo box. 的本地化字符串。
        /// </summary>
        public static string Msgbox_ModelNotSelected {
            get {
                return ResourceManager.GetString("Msgbox_ModelNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No file loaded. (No tpac file in any sub directory) 的本地化字符串。
        /// </summary>
        public static string Msgbox_NoFileLoaded {
            get {
                return ResourceManager.GetString("Msgbox_NoFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to select a skeleton from the combo box. 的本地化字符串。
        /// </summary>
        public static string Msgbox_SkeletonNotSelected {
            get {
                return ResourceManager.GetString("Msgbox_SkeletonNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tpac file found in the top directory. Go on? (Will search sub directories) 的本地化字符串。
        /// </summary>
        public static string Msgbox_TpacNotFound {
            get {
                return ResourceManager.GetString("Msgbox_TpacNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Msgbox_Warning {
            get {
                return ResourceManager.GetString("Msgbox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus: 的本地化字符串。
        /// </summary>
        public static string Preview_Center {
            get {
                return ResourceManager.GetString("Preview_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center of Geometry 的本地化字符串。
        /// </summary>
        public static string Preview_Center_Geometry {
            get {
                return ResourceManager.GetString("Preview_Center_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center of Mass 的本地化字符串。
        /// </summary>
        public static string Preview_Center_Mass {
            get {
                return ResourceManager.GetString("Preview_Center_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin 的本地化字符串。
        /// </summary>
        public static string Preview_Center_Origin {
            get {
                return ResourceManager.GetString("Preview_Center_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the focal point of rotation and scaling. 的本地化字符串。
        /// </summary>
        public static string Preview_Center_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Center_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Inertia 的本地化字符串。
        /// </summary>
        public static string Preview_Inertia {
            get {
                return ResourceManager.GetString("Preview_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable inertia for mouse rotation and zoom. 的本地化字符串。
        /// </summary>
        public static string Preview_Inertia_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Inertia_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Scale 的本地化字符串。
        /// </summary>
        public static string Preview_Keepscale {
            get {
                return ResourceManager.GetString("Preview_Keepscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep the scale of the preview model in the screen when selecting other asset. 的本地化字符串。
        /// </summary>
        public static string Preview_Keepscale_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Keepscale_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lights: 的本地化字符串。
        /// </summary>
        public static string Preview_Lights {
            get {
                return ResourceManager.GetString("Preview_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quad Lights 的本地化字符串。
        /// </summary>
        public static string Preview_Lights_Quad {
            get {
                return ResourceManager.GetString("Preview_Lights_Quad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Light 的本地化字符串。
        /// </summary>
        public static string Preview_Lights_Single {
            get {
                return ResourceManager.GetString("Preview_Lights_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the light sources in the scene. 的本地化字符串。
        /// </summary>
        public static string Preview_Lights_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Lights_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tri Lights 的本地化字符串。
        /// </summary>
        public static string Preview_Lights_Tri {
            get {
                return ResourceManager.GetString("Preview_Lights_Tri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot preview this texture because its format is unsupported: {0} 的本地化字符串。
        /// </summary>
        public static string Preview_Msg_TextureFormatUnsupported {
            get {
                return ResourceManager.GetString("Preview_Msg_TextureFormatUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot preview nor export this texture because its data are stored in the external TileSets file. 的本地化字符串。
        /// </summary>
        public static string Preview_Msg_TextureHasNoData {
            get {
                return ResourceManager.GetString("Preview_Msg_TextureHasNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot preview this texture because of its size (&gt;100MB) 的本地化字符串。
        /// </summary>
        public static string Preview_Msg_TextureSizeTooLarge {
            get {
                return ResourceManager.GetString("Preview_Msg_TextureSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale Inertia 的本地化字符串。
        /// </summary>
        public static string Preview_Scale_Inertia {
            get {
                return ResourceManager.GetString("Preview_Scale_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable inertia for camera scaling when changing model. 的本地化字符串。
        /// </summary>
        public static string Preview_Scale_Inertia_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Scale_Inertia_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Grid 的本地化字符串。
        /// </summary>
        public static string Preview_Showgrid {
            get {
                return ResourceManager.GetString("Preview_Showgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the grid of ground. 的本地化字符串。
        /// </summary>
        public static string Preview_Showgrid_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Showgrid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transition Inertia 的本地化字符串。
        /// </summary>
        public static string Preview_Transition_Inertia {
            get {
                return ResourceManager.GetString("Preview_Transition_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable inertia for camera transition when changing model. 的本地化字符串。
        /// </summary>
        public static string Preview_Transition_Inertia_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Transition_Inertia_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export texture to ... 的本地化字符串。
        /// </summary>
        public static string Texture_Dialog_SelectExportFile {
            get {
                return ResourceManager.GetString("Texture_Dialog_SelectExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Texture_Export {
            get {
                return ResourceManager.GetString("Texture_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suggested format: {0} 的本地化字符串。
        /// </summary>
        public static string Texture_Export_SuggestedFormat {
            get {
                return ResourceManager.GetString("Texture_Export_SuggestedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flags 的本地化字符串。
        /// </summary>
        public static string Texture_Flags {
            get {
                return ResourceManager.GetString("Texture_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Texture_Preview {
            get {
                return ResourceManager.GetString("Texture_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channal 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alpha 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel_Alpha {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel_Auto {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B as Gray 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel_BGray {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_BGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G as Gray 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel_GGray {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_GGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R as Gray 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel_RGray {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_RGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Which color channels are displayed during preview. 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Channel_Tooltip {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clamp 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Clamp {
            get {
                return ResourceManager.GetString("Texture_Preview_Clamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Size 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Clamp_Full {
            get {
                return ResourceManager.GetString("Texture_Preview_Clamp_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restrict the size of the preview texture. Smaller clamp size can make the texture load faster. 的本地化字符串。
        /// </summary>
        public static string Texture_Preview_Clamp_Tooltip {
            get {
                return ResourceManager.GetString("Texture_Preview_Clamp_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string Texture_Properties {
            get {
                return ResourceManager.GetString("Texture_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array: 的本地化字符串。
        /// </summary>
        public static string Texture_Properties_Array {
            get {
                return ResourceManager.GetString("Texture_Properties_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format: 的本地化字符串。
        /// </summary>
        public static string Texture_Properties_Format {
            get {
                return ResourceManager.GetString("Texture_Properties_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Texture_Properties_Info {
            get {
                return ResourceManager.GetString("Texture_Properties_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mipmap: 的本地化字符串。
        /// </summary>
        public static string Texture_Properties_Mipmap {
            get {
                return ResourceManager.GetString("Texture_Properties_Mipmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string Texture_Properties_Size {
            get {
                return ResourceManager.GetString("Texture_Properties_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Flags 的本地化字符串。
        /// </summary>
        public static string Texture_System_Flags {
            get {
                return ResourceManager.GetString("Texture_System_Flags", resourceCulture);
            }
        }
    }
}
